// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: suggestService.proto

#include "suggestService.pb.h"
#include "suggestService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace suggestService {

static const char* SuggestService_method_names[] = {
  "/suggestService.SuggestService/Hello",
};

std::unique_ptr< SuggestService::Stub> SuggestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SuggestService::Stub> stub(new SuggestService::Stub(channel));
  return stub;
}

SuggestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Hello_(SuggestService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SuggestService::Stub::Hello(::grpc::ClientContext* context, const ::suggestService::SuggestRequest& request, ::suggestService::SuggestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::suggestService::SuggestRequest, ::suggestService::SuggestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Hello_, context, request, response);
}

void SuggestService::Stub::experimental_async::Hello(::grpc::ClientContext* context, const ::suggestService::SuggestRequest* request, ::suggestService::SuggestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::suggestService::SuggestRequest, ::suggestService::SuggestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, std::move(f));
}

void SuggestService::Stub::experimental_async::Hello(::grpc::ClientContext* context, const ::suggestService::SuggestRequest* request, ::suggestService::SuggestResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::suggestService::SuggestResponse>* SuggestService::Stub::PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::suggestService::SuggestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::suggestService::SuggestResponse, ::suggestService::SuggestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Hello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::suggestService::SuggestResponse>* SuggestService::Stub::AsyncHelloRaw(::grpc::ClientContext* context, const ::suggestService::SuggestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

SuggestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SuggestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SuggestService::Service, ::suggestService::SuggestRequest, ::suggestService::SuggestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SuggestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::suggestService::SuggestRequest* req,
             ::suggestService::SuggestResponse* resp) {
               return service->Hello(ctx, req, resp);
             }, this)));
}

SuggestService::Service::~Service() {
}

::grpc::Status SuggestService::Service::Hello(::grpc::ServerContext* context, const ::suggestService::SuggestRequest* request, ::suggestService::SuggestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace suggestService

